@startuml Admin_Clinical
title ADMIN — Appointments / Visits / Prescriptions

left to right direction
skinparam actorStyle awesome
skinparam packageStyle rectangle
skinparam ranksep 60
skinparam nodesep 30
skinparam usecase {
  BackgroundColor #FFF4EE
  BorderColor #D9734A
  FontSize 12
}
skinparam package {
  BackgroundColor #FFFBF9
  BorderColor #D9734A
  FontSize 13
  FontStyle bold
}

actor "Admin" as A #D9734A

package "Appointments" {
  (عرض المواعيد)
  (إضافة موعد)
  (تعديل موعد)
  (حذف موعد)
}

package "Visits" {
  (عرض الزيارات)
  (تسجيل زيارة)
  (تعديل زيارة)
}

package "Prescriptions" {
  (عرض الوصفات)
  (كتابة وصفة)
  (تعديل وصفة)
}

A --> (عرض المواعيد)
A --> (إضافة موعد)
A --> (تعديل موعد)
A --> (حذف موعد)

A --> (عرض الزيارات)
A --> (تسجيل زيارة)
A --> (تعديل زيارة)

A --> (عرض الوصفات)
A --> (كتابة وصفة)
A --> (تعديل وصفة)

@enduml
